services:
  - type: web
    name: incubadora-backend
    env: docker
    dockerfilePath: Dockerfile
    dockerContext: .
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "true"
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        value: https://backenencuvadora-2-9tl9.onrender.com
      - key: APP_NAME
        value: UniIncubadora
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: FRONTEND_URL
        value: https://fronteencuvadora-qxys.vercel.app
      - key: ALLOWED_ORIGINS
        value: https://fronteencuvadora-qxys.vercel.app
      - key: SANCTUM_STATEFUL_DOMAINS
        value: fronteencuvadora-qxys.vercel.app
      - key: SESSION_DRIVER
        value: cookie
      - key: QUEUE_CONNECTION
        value: sync
      - key: CACHE_STORE
        value: file
      - key: FILESYSTEM_DISK
        value: local
      - key: LOG_CHANNEL
        value: stack
      - key: LOG_LEVEL
        value: debug
