services:
  - type: web
    name: incubadora-backend
    env: docker
    dockerfilePath: Dockerfile
    dockerContext: .
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "true"
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        value: https://backenencuvadora-2-9tl9.onrender.com
      - key: APP_NAME
        value: UniIncubadora
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: ep-blue-cherry-atpxkltu-pooler.c-9.us-east-1.aws.neon.tech
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        value: neondb
      - key: DB_USERNAME
        value: neondb_owner
      - key: DB_PASSWORD
        value: npg_KLgGlT5j1WqN
      - key: FRONTEND_URL
        value: https://incubadoraunesum.com
      - key: ALLOWED_ORIGINS
        value: https://incubadoraunesum.com,https://www.incubadoraunesum.com,https://fronteencuvadora-qxys.vercel.app
      - key: SANCTUM_STATEFUL_DOMAINS
        value: incubadoraunesum.com,www.incubadoraunesum.com,fronteencuvadora-qxys.vercel.app
      - key: SESSION_DRIVER
        value: cookie
      - key: QUEUE_CONNECTION
        value: sync
      - key: CACHE_STORE
        value: file
      - key: FILESYSTEM_DISK
        value: local
      - key: LOG_CHANNEL
        value: stack
      - key: LOG_LEVEL
        value: debug
